### ISSUE TITLE
Crash on startup with 1.19.2-3.3.0

### ISSUE THREAD

**Issue by brisingraerowing** [Sarenor/Ars-Instrumentum#9]
```text
[10:30:38] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: ars_instrumentum, class de.sarenor.arsinstrumentum.ArsInstrumentum
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.8.jar%231028!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.8.jar%231027!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) [?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?] {}
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.world.item.Item$Properties net.minecraft.world.item.Item$Properties.tab(net.minecraft.world.item.CreativeModeTab)'
	at de.sarenor.arsinstrumentum.setup.Registration.<clinit>(Registration.java:32) ~[ars_instrumentum-1.19.2-3.3.0.jar%23607!/:3.3.0] {re:classloading}
	at de.sarenor.arsinstrumentum.ArsInstrumentum.<init>(ArsInstrumentum.java:25) ~[ars_instrumentum-1.19.2-3.3.0.jar%23607!/:3.3.0] {re:classloading}
	... 14 more
```

This pops up in the log on startup. Obfuscation error?

**Comment by Sarenor** [comment]
Probably accidentally broke my data gen. How do you people update so quickly, it was listed for like 5 hours before I noticed the error and archived it!

Fixed version should be going out soon

**Comment by Sarenor** [comment]
https://www.curseforge.com/minecraft/mc-mods/ars-instrumentum/files/4482648

Soon as curseforge is done checking, 3.3.1 should be available here

**Comment by brisingraerowing** [comment]
I saw the update a couple hours after it was approved. Just good (bad?) timing, I suppose.

**Comment by Sarenor** [comment]
Bad in this case. Sorry for any pain it caused!
